# Generated by Django 4.1.7 on 2023-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ususario', models.CharField(max_length=255)),
                ('Orden', models.CharField(max_length=255)),
            ],
        ),
    ]
