# Generated by Django 4.1.7 on 2023-03-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remesas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Ususario',
            new_name='Usuario',
        ),
    ]
